# Site locale
lang: "en"

remote_theme: pages-themes/architect@v0.2.0

title: vd Brink Home Automations
description: "Home automations: Home Assistant, ESPHome, Node-RED and more."
url: https://vdbrink.github.io

google_analytics: G-WTTK5G664M

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# Tags
tag_page_layout: tag_page
tag_page_dir: tag

# Use the following plug-ins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll/tagging
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - webrick
  - jekyll-github-metadata

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md